### ISSUE TITLE
Minor issue with JSON Decoding C#/F#

### ISSUE THREAD

**Issue by josueespinosa** [itsmeichigo/Fretboard#1]
This is awesome, did you generate the guitar/ukulele json yourself? 

Only small thing to fix is that in the guitar json, C# and F# are written as "CSharp" etc so when you select them in the dropdown, the fretboard doesn't update since the name isn't found in the json. Replacing them with C# and F# fixes the bug.

Thank you for this project, very useful!

**Comment by itsmeichigo** [comment]
Thank you @josueespinosa  for letting me know of the issue! This has been fixed in 0803c3432702c3ffbd925fd3d0a56024d9bffe22 🎉
